export const predictions = [
  {
    event: "Russia-Ukraine Conflict Escalation",
    probability: 78,
    timeframe: "Next 45 days",
    impact: "Critical",
    affectedSectors: ["Energy", "Agriculture", "Defense"],
    businessImpact: "$2.3B in supply chain disruptions",
  },
  {
    event: "China Taiwan Military Exercise",
    probability: 41,
    timeframe: "Next 60 days",
    impact: "High",
    affectedSectors: ["Semiconductors", "Manufacturing", "Shipping"],
    businessImpact: "$890M in semiconductor shortages",
  },
  {
    event: "Iran Nuclear Deal Collapse",
    probability: 67,
    timeframe: "Next 30 days",
    impact: "Medium-High",
    affectedSectors: ["Oil & Gas", "Financial Services"],
    businessImpact: "$1.2B in energy price volatility",
  },
  {
    event: "Turkey Economic Crisis Deepening",
    probability: 89,
    timeframe: "Next 30 days",
    impact: "Medium",
    affectedSectors: ["Banking", "Tourism", "Manufacturing"],
    businessImpact: "$450M in currency exposure",
  },
  {
    event: "EU Tech Regulation Expansion",
    probability: 92,
    timeframe: "Next 90 days",
    impact: "Medium",
    affectedSectors: ["Technology", "Data Services", "AI"],
    businessImpact: "$320M in compliance costs",
  },
]

export const countryRisks = {
  "United States": { overall: 23, political: 35, economic: 15, security: 18 },
  China: { overall: 52, political: 68, economic: 45, security: 43 },
  Russia: { overall: 87, political: 92, economic: 85, security: 84 },
  Ukraine: { overall: 95, political: 98, economic: 94, security: 97 },
  Germany: { overall: 18, political: 12, economic: 22, security: 20 },
  Iran: { overall: 78, political: 85, economic: 72, security: 76 },
  Turkey: { overall: 65, political: 70, economic: 75, security: 50 },
  Taiwan: { overall: 48, political: 55, economic: 35, security: 65 },
  "United Kingdom": { overall: 25, political: 30, economic: 28, security: 15 },
  France: { overall: 22, political: 25, economic: 20, security: 18 },
}

export const intelligenceUpdates = [
  {
    id: 1,
    timestamp: "2 min ago",
    headline: "Russia announces new military exercises near Ukrainian border, raising tensions",
    source: "Reuters",
    credibility: 95,
    impact: "High",
    category: "Military",
    region: "Eastern Europe",
    sentiment: -0.7,
    engagement: { likes: 234, shares: 89, comments: 45 },
  },
  {
    id: 2,
    timestamp: "15 min ago",
    headline: "China's semiconductor exports drop 15% amid ongoing trade restrictions",
    source: "Bloomberg",
    credibility: 93,
    impact: "Medium",
    category: "Economic",
    region: "Asia Pacific",
    sentiment: -0.4,
    engagement: { likes: 156, shares: 67, comments: 23 },
  },
  {
    id: 3,
    timestamp: "32 min ago",
    headline: "Iran resumes uranium enrichment activities, nuclear deal prospects dim",
    source: "Financial Times",
    credibility: 91,
    impact: "High",
    category: "Political",
    region: "Middle East",
    sentiment: -0.6,
    engagement: { likes: 198, shares: 112, comments: 78 },
  },
  {
    id: 4,
    timestamp: "1 hour ago",
    headline: "Turkish lira hits new record low as inflation concerns mount",
    source: "Reuters",
    credibility: 94,
    impact: "Medium",
    category: "Economic",
    region: "Europe/Middle East",
    sentiment: -0.8,
    engagement: { likes: 87, shares: 34, comments: 12 },
  },
  {
    id: 5,
    timestamp: "1.5 hours ago",
    headline: "EU proposes new sanctions package targeting Russian energy sector",
    source: "Bloomberg",
    credibility: 92,
    impact: "High",
    category: "Political",
    region: "Europe",
    sentiment: -0.3,
    engagement: { likes: 267, shares: 145, comments: 89 },
  },
  {
    id: 6,
    timestamp: "2 hours ago",
    headline: "Taiwan reports increased Chinese military aircraft in defense zone",
    source: "Reuters",
    credibility: 96,
    impact: "Medium",
    category: "Military",
    region: "Asia Pacific",
    sentiment: -0.5,
    engagement: { likes: 178, shares: 92, comments: 56 },
  },
  {
    id: 7,
    timestamp: "3 hours ago",
    headline: "Global oil prices surge 3% on Middle East supply concerns",
    source: "Financial Times",
    credibility: 89,
    impact: "Medium",
    category: "Economic",
    region: "Global",
    sentiment: -0.2,
    engagement: { likes: 134, shares: 78, comments: 34 },
  },
  {
    id: 8,
    timestamp: "4 hours ago",
    headline: "NATO announces enhanced presence in Eastern European member states",
    source: "Reuters",
    credibility: 97,
    impact: "High",
    category: "Military",
    region: "Europe",
    sentiment: 0.1,
    engagement: { likes: 289, shares: 167, comments: 123 },
  },
]
